# Generated by Django 5.0.6 on 2024-05-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topics_room_host_message_room_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
    ]
